### ISSUE TITLE
Mautic 3

### ISSUE THREAD

**Issue by deggertsen** [vdavid/node-mautic#14]
Are there any known issues with using Mautic 3? I've been doing some testing and my api calls are failing with a "SyntaxError: Unexpected token < in JSON at position 0"
I'm not sure if that has anything to do with this library, but I thought I would reach out to check.

**Comment by vdavid** [comment]
I still use Mautic 2.x, so no, I personally haven’t tested with 3.x unfortunately.
The "SyntaxError: Unexpected token < in JSON at position 0" happens if Mautic returns with an HTML response instead of a JSON – typically an error message. Use a breakpoint or logging to figure out what the error message is. I’m unsure how much the API has changed between 2.x and 3.x. If they’re close then you can probably resolve it. If they’re very different, then I’ll make it compatible in a few months when we also do the upgrade.

**Comment by antesant** [comment]
Having the same issue. editContact method responds with `failed, reason: socket hang up`

**Comment by vdavid** [comment]
Update: at my company we're upgrading to Mautic 3.1. We'll test this package with the new version soon. I will post an update here when that happens.

**Comment by antesant** [comment]
@vdavid Sweet! Any updates on this?

**Comment by vdavid** [comment]
Thanks for the ping @antesant. At my company we updated Mautic to 3.1.2, and the package works well with it. I’ve done some housekeeping too (NPM package updates, README.md update, logging improvements, code style uniformization, added ‘stats’ Mautic API, added missing JSDoc) and released the result as 1.2.0. I'm closing this issue.
